app/tone/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields import StringField, SubmitField, DateField, IntegerField, FloatField


class ToneForm(FlaskForm):
    dic_code = IntegerField("体检项目编码")
    summary = StringField("体检项对应的健康状态描述")
    val = IntegerField("权重")
    lower_scope = FloatField("范围下限")
    upper_scope = FloatField("范围上限")
    submit = SubmitField("更新")

app/tone/__init__.py
from flask import Blueprint

tone = Blueprint("tone", __name__)

from . import views, forms

app/tone/views.py
from flask import render_template, redirect, url_for
from . import tone
from ..models import TblDictTone, TblCity, db
from sqlalchemy import alias
from .forms import ToneForm


@tone.route("/dict_list")
def dict_list():
    data = db.session.query(TblDictTone).all()
    return render_template("tone/dict_list.html", data=data)


@tone.route("/tone/update/<int:id>", methods=['GET', 'POST'])
def update(id):
    tone = TblDictTone.query.get(id)
    form = ToneForm()
    if form.validate_on_submit():
        tone.dict_code = form.dic_code.data
        tone.summary = form.summary.data
        tone.val = form.val.data
        tone.lower_scope = form.lower_scope.data
        tone.upper_scope = form.upper_scope.data
        db.session.add(tone)
        db.session.commit()
        return redirect(url_for("tone.dict_list"))
    form.dic_code.data = tone.dic_code
    form.summary.data = tone.summary
    form.val.data = tone.val
    form.lower_scope.data = tone.lower_scope
    form.upper_scope.data = tone.lower_scope
    return render_template("tone/tone_update.html", form=form)


@tone.route("/tone/create", methods=['GET', 'POST'])
def create():
    form = ToneForm()
    if form.validate_on_submit():
        tone = TblDictTone()
        tone.dic_code = form.dic_code.data
        tone.summary = form.summary.data
        tone.val = form.val.data
        tone.lower_scope = form.lower_scope.data
        tone.upper_scope = form.upper_scope.data
        db.session.add(tone)
        db.session.commit()
        return redirect(url_for("tone.dict_list"))
    return render_template("tone/tone_update.html", form=form)


@tone.route("/tone/delete/<int:id>", methods=['POST', 'GET'])
def delete(id):
    tone = TblDictTone.query.get(id)
    db.session.delete(tone)
    db.session.commit()
    return redirect(url_for("tone.dict_list"))

app/templates/tone/dict_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

    <table class="table table-bordered table-responsive">
        <thead>
        <tr>
            <th>体检项目ID</th>
            <th>健康级别</th>
            <th>范围下限</th>
            <th>范围上限</th>
            <th>权值</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for d in data %}
            <tr>
                <td>{{ d.dic_code }}</td>
                <td>{{ d.summary }}</td>
                <td>{{ d.lower_scope }}</td>
                <td>{{ d.upper_scope }}</td>
                <td>{{ d.val }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ url_for('tone.update',id=d.tone_id) }}">更新</a>
                    <a class="btn btn-danger" href="{{ url_for('tone.delete',id=d.tone_id) }}">删除</a>
                </td>
            </tr>
        {% endfor %}


    </table>
    <a class="btn btn-primary col-md-4" href="{{ url_for('tone.create') }}">新增</a>
{% endblock %}

app/templates/tone/tone_update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    <div class="col-md-6">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}