app/dic_cmp_conduct/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields import StringField, SubmitField, DateField, IntegerField, FloatField, SelectField
from ..models import TblDictTone


class DictCmpConductForm(FlaskForm):
    dic_code = IntegerField("体检项目编码")
    tone_id = SelectField("针对的体检项目及其级别", coerce=int)
    suggest = StringField("建议")
    risk = StringField("风险分析")
    submit = SubmitField("更新")

    def __init__(self, *args, **kwargs):
        super(DictCmpConductForm, self).__init__(*args, **kwargs)
        self.tone_id.choices = [(tone.tone_id, tone.summary)
                                for tone in
                                TblDictTone.query.order_by(TblDictTone.tone_id).all()]

app/dic_cmp_conduct/__init__.py
from flask import Blueprint

dict_cmp_conduct = Blueprint("dict_cmp_conduct", __name__)

from . import views, forms

app/dic_cmp_conduct/views.py
from flask import render_template, redirect, url_for
from . import dict_cmp_conduct
from ..models import TblDictCmpConduct, TblCity, TblDictTone, db
from sqlalchemy import alias
from .forms import DictCmpConductForm


@dict_cmp_conduct.route("/conduct/list")
def list():
    data = db.session.query(TblDictCmpConduct).all()
    tones = db.session.query(TblDictTone).all()
    # tone_map = [(tone.tone_id, str(tone.dic_code) + " :" + tone.summary)
    #             for tone in
    #             TblDictTone.query.order_by(TblDictTone.tone_id).all()]
    tone_map = {tone.tone_id: tone.summary
                for tone in tones
                }
    return render_template("dic_cmp_conduct/dict_cmp_conduct_list.html", data=data, tone_map=tone_map)


@dict_cmp_conduct.route("/conduct/update/<int:id>", methods=['GET', 'POST'])
def update(id):
    dict_cmp_accord = TblDictCmpConduct.query.get(id)
    form = DictCmpConductForm()
    if form.validate_on_submit():
        dict_cmp_accord.dic_code = form.dic_code.data
        dict_cmp_accord.tone_id = form.tone_id.data
        dict_cmp_accord.suggest = form.suggest.data
        dict_cmp_accord.risk = form.risk.data
        db.session.add(dict_cmp_accord)
        db.session.commit()
        return redirect(url_for("dict_cmp_conduct.list"))
    form.dic_code.data = dict_cmp_accord.dic_code
    form.tone_id.data = dict_cmp_accord.tone_id
    form.suggest.data = dict_cmp_accord.suggest
    form.risk.data = dict_cmp_accord.risk

    return render_template("dic_cmp_conduct/dict_cmp_conduct_update.html", form=form)


@dict_cmp_conduct.route("/conduct/create", methods=['GET', 'POST'])
def create():
    form = DictCmpConductForm()
    if form.validate_on_submit():
        dict_cmp_conduct = TblDictCmpConduct()
        dict_cmp_conduct.dic_code = form.dic_code.data
        dict_cmp_conduct.tone_id = form.tone_id.data

        dict_cmp_conduct.suggest = form.suggest.data
        dict_cmp_conduct.risk = form.risk.data
        db.session.add(dict_cmp_conduct)
        db.session.commit()
        return redirect(url_for("dict_cmp_conduct.list"))
    return render_template("dic_cmp_conduct/dict_cmp_conduct_update.html", form=form)


@dict_cmp_conduct.route("/conduct/delete/<int:id>", methods=['POST', 'GET'])
def delete(id):
    dict_cmp_conduct = TblDictCmpConduct.query.get(id)
    db.session.delete(dict_cmp_conduct)
    db.session.commit()
    return redirect(url_for("dict_cmp_conduct.list"))

app/templates/dic_cmp_conduct/dict_cmp_conduct_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

    <table class="table table-bordered table-responsive">
        <thead>
        <tr>
            <th>体检项目ID</th>
            <th>健康状态</th>
            <th>建议</th>
            <th>风险描述</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for d in data %}
            <tr>
                <td>{{ d.dic_code }}</td>
                <td>{{ tone_map[d.tone_id] }}</td>
                <td>{{ d.suggest }}</td>
                <td>{{ d.risk }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ url_for('dict_cmp_conduct.update',id=d.id) }}">更新</a>
                    <a class="btn btn-danger" href="{{ url_for('dict_cmp_conduct.delete',id=d.id) }}">删除</a>
                </td>
            </tr>
        {% endfor %}


    </table>
    <a class="btn btn-primary col-md-4" href="{{ url_for('dict_cmp_conduct.create') }}">新增</a>
{% endblock %}

app/templates/dic_cmp_conduct/dict_cmp_conduct_update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    <div class="col-md-6">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}