app/dict_cmp_accord/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields import StringField, SubmitField, DateField, IntegerField, FloatField, SelectField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from ..models import TblDictTone
from .. import photos


class DictCmpAccordForm(FlaskForm):
    dic_code = IntegerField("体检项目编码")
    ahead_tone = SelectField("相对过去的健康状态", coerce=int)
    behead_tone = SelectField("相对现在的健康状态", coerce=int)
    trend_advise = StringField("对比过去和现在的健康趋势，对应的建议")
    img = FileField('图片上传', validators=[
        FileAllowed(photos, '只能上传图片！'),
        FileRequired('文件未选择！')
    ])

    def __init__(self, *args, **kwargs):
        super(DictCmpAccordForm, self).__init__(*args, **kwargs)
        self.ahead_tone.choices = [(tone.val, str(tone.dic_code) + " :" + tone.summary)
                                   for tone in
                                   TblDictTone.query.order_by(TblDictTone.tone_id).all()]
        self.behead_tone.choices = [(tone.val, str(tone.dic_code) + " :" + tone.summary)
                                    for tone in
                                    TblDictTone.query.order_by(TblDictTone.tone_id).all()]

    submit = SubmitField("更新")

app/dict_cmp_accord/__init__.py
from flask import Blueprint

dict_cmp_accord = Blueprint("dict_cmp_accord", __name__)

from . import views, forms

app/dict_cmp_accord/views.py
from flask import render_template, redirect, url_for
from . import dict_cmp_accord
from ..models import TblDictCmpAccord, TblCity, db
from sqlalchemy import alias
from .forms import DictCmpAccordForm

from .. import photos
from config import Config
import os


@dict_cmp_accord.route("/list")
def list():
    data = db.session.query(TblDictCmpAccord).all()
    return render_template("dict_cmp_accord/dict_cmp_accord_list.html", data=data)


@dict_cmp_accord.route("/update/<int:id>", methods=['GET', 'POST'])
def update(id):
    dict_cmp_accord = TblDictCmpAccord.query.get(id)
    form = DictCmpAccordForm()
    if form.validate_on_submit():
        dict_cmp_accord.dic_code = form.dic_code.data
        dict_cmp_accord.ahead_tone = form.ahead_tone.data
        dict_cmp_accord.behead_tone = form.behead_tone.data

        filename = form.img.data.filename
        print('上传图片：', filename)
        print('本地图片', os.listdir(Config.UPLOADED_PHOTOS_DEST))
        if form.img.data.filename in os.listdir(Config.UPLOADED_PHOTOS_DEST):
            dict_cmp_accord.img = form.img.data.filename
            db.session.add(dict_cmp_accord)
            db.session.commit()
            return redirect(url_for("dict_cmp_accord.list"))
        filename = photos.save(form.img.data, name=filename)
        dict_cmp_accord.trend_advise = form.trend_advise.data

        dict_cmp_accord.img = filename
        db.session.add(dict_cmp_accord)
        db.session.commit()
        return redirect(url_for("dict_cmp_accord.list"))
    form.dic_code.data = dict_cmp_accord.dic_code
    form.ahead_tone.data = dict_cmp_accord.ahead_tone
    form.behead_tone.data = dict_cmp_accord.behead_tone
    form.trend_advise.data = dict_cmp_accord.trend_advise
    form.img.data = photos.url(dict_cmp_accord.img)
    return render_template("dict_cmp_accord/dict_cmp_accord_update.html", form=form)


@dict_cmp_accord.route("/create", methods=['GET', 'POST'])
def create():
    form = DictCmpAccordForm()
    if form.validate_on_submit():
        dict_cmp_accord = TblDictCmpAccord()
        dict_cmp_accord.dic_code = form.dic_code.data
        dict_cmp_accord.ahead_tone = form.ahead_tone.data
        dict_cmp_accord.behead_tone = form.behead_tone.data
        dict_cmp_accord.trend_advise = form.trend_advise.data
        db.session.add(dict_cmp_accord)
        db.session.commit()
        return redirect(url_for("dict_cmp_accord.list"))
    return render_template("dict_cmp_accord/dict_cmp_accord_update.html", form=form)


@dict_cmp_accord.route("/delete/<int:id>", methods=['POST', 'GET'])
def delete(id):
    dict_cmp_accord = TblDictCmpAccord.query.get(id)
    db.session.delete(dict_cmp_accord)
    db.session.commit()
    return redirect(url_for("dict_cmp_accord.list"))

app/templates/dict_cmp_accord/dict_cmp_accord_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

    <table class="table table-bordered table-responsive">
        <thead>
        <tr>
            <th>体检项目ID</th>
            <th>上次的健康状态权值</th>
            <th>目前的健康状态权值</th>
            <th>健康状态趋势建议</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for d in data %}
            <tr>
                <td>{{ d.dic_code }}</td>
                <td>{{ d.ahead_tone }}</td>
                <td>{{ d.behead_tone }}</td>
                <td>{{ d.trend_advise }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ url_for('dict_cmp_accord.update',id=d.cmp_accord_id) }}">更新</a>
                    <a class="btn btn-danger" href="{{ url_for('dict_cmp_accord.delete',id=d.cmp_accord_id) }}">删除</a>
                </td>
            </tr>
        {% endfor %}


    </table>
    <a class="btn btn-primary col-md-4" href="{{ url_for('dict_cmp_accord.create') }}">新增</a>
{% endblock %}

app/templates/dict_cmp_accord/dict_cmp_accord_update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    <div class="col-md-6">
        {{ wtf.quick_form(form,enctype="multipart/form-data") }}
    </div>
{% endblock %}